spring.application.name=wifi-ai-analyzer
spring.datasource.url=jdbc:postgresql://localhost:5432/wifi_ai_analyzer_db
spring.datasource.username=wifi
spring.datasource.password=wifi

spring.jpa.hibernate.ddl-auto=update
